apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "intel_sriov_ixgbevf",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["10ed"],
                    "drivers": ["ixgbevf"],
                    "pciAddresses": ["0000:00:04.0","0000:00:05.0","0000:00:06.0"]
                }
            }
        ]
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n3-dp-net
  namespace: open5gs
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_ixgbevf
spec:
  config: '{
            "cniVersion": "0.3.1",
            "plugins": [
                {
                    "type": "host-device",
                    "capabilities": { "ips": true },
                    "ipam": {
                        "type": "static",
                        "routes": [{
			  "dst": "0.0.0.0/0"
			}]
                    }
                }]
        }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n6-dp-net
  namespace: open5gs
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_ixgbevf
spec:
  config: '{
            "cniVersion": "0.3.1",
            "plugins": [
                {
                    "type": "host-device",
                    "capabilities": { "ips": true },
                    "ipam": {
                        "type": "static",
                        "routes": [{
			  "dst": "0.0.0.0/0"
			}]
                    }
                }]
        }'
        
